# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  Default

variables:
  buildConfiguration: 'Release'

  working_directory: /FlightBookingBackend

steps:

- script: dotnet build FlightBookingBackend/FlightBookingBackend.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
